version: '3'

services:
  wercker.teamservice:
    image: wercker.teamservice
    build:
      context: ./src/Wercker.TeamService
      dockerfile: Dockerfile

  wercker.web:
    image: wercker.web
    build:
      context: ./src/Wercker.Web
      dockerfile: Dockerfile
